# The default colors
foreground #dee3e6
background #0f1417

# Selection highlight
selection_foreground #cfe6f1
selection_background #354a53

# The cursor colors
cursor #89d0ee
cursor_text_color #003545

# URL color
url_color #dce0e0

# ANSI colors
## Normal colors (0-7)
color0  #252b2d
color1  #ffb4ab
color2  #89d0ee
color3  #c5c3ea
color4  #b4cad5
color5  #bbeaff
color6  #cfe6f1
color7  #c0c8cc
## Bright colors (8-15)
color8  #8a9296
color9  #93000a
color10 #004d62
color11 #444465
color12 #354a53
color13 #0d6681
color14 #40484c
color15 #dee3e6

# Tab colors (optional, using Material You accents)
active_tab_foreground #003545
active_tab_background #89d0ee
inactive_tab_foreground #c0c8cc
inactive_tab_background #1b2023

# Border colors
active_border_color #89d0ee
inactive_border_color #303638
bell_border_color #e9efee

# Marks (optional)
mark1_foreground #001f29
mark1_background #bbeaff
