general {
  lock_cmd = pidof hyprlock || hyprlock   # avoid starting multiple hyprlock instances.
  before_sleep_cmd = hyprlock             # lock before suspend.
}

listener {
  timeout = 600
  # Lock the screen
  on-timeout = hyprlock
}

listener {
  timeout = 660
  # Turn the screen OFF on timeout
  on-timeout = hyprctl dispatch dpms off
  # Turn the screen ON when you move mouse/press key
  on-resume = hyprctl dispatch dpms on
}
