-- Generated by Matugen
local M = {}

M.image = "{{image}}"

-- Dynamic loop over all colors
local colors = {
<* for name, value in colors *>
    {{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
}

-- Merge colors into the main module export
for k, v in pairs(colors) do
    M[k] = v
end

return M
